export const SEARCH_REPO_START = "SEARCH_REPO_START";
export const SEARCH_REPO_SUCCESS = "SEARCH_REPO_SUCCESS";
export const SEARCH_REPO_FAILURE = "SEARCH_REPO_FAILURE";

export const SELECT_COMMIT_START = "SELECT_COMMIT_START";
export const SELECT_COMMIT_SUCCESS = "SELECT_COMMIT_SUCCESS";
export const SELECT_COMMIT_FAILURE = "SELECT_COMMIT_FAILURE";
